### ISSUE TITLE
Unsupported major.minor version

### ISSUE THREAD

**Issue by dehimb** [kgmyshin/eventbus-intellij-plugin#2]
I have this error when try to use plugin with latest Android Studio
com/kgmyshin/ideaplugin/eventbus/EventBusLineMarkerProvider : Unsupported major.minor version 51.0 [Plugin: com.kgmyshin.ideaplugin.eventbus]

**Comment by kgmyshin** [comment]
@dehimb 

I think you use JDK6 and if you use JDK7, that error will be eliminated.

But if you want to JDK6, I can try to correspond that.

**Comment by dehimb** [comment]
@kgmyshin
I change jdk version and it helps, thanks.

**Comment by kgmyshin** [comment]
:+1:
