### ISSUE TITLE
Not working for Eventbus 2.4.0

### ISSUE THREAD

**Issue by dheerajbhaskar** [kgmyshin/eventbus-intellij-plugin#5]
# Problem

Clicking on the android image on the left at a post location says no subscribers found in project files. However, there's a subscriber in the same file. Images attached show the situation

I'm using Eventbus 2.4.0

**1 base state**
![1 base state](https://cloud.githubusercontent.com/assets/2944909/8762469/340c8890-2d97-11e5-83ab-34fda23ec955.png)

**2 click on the android icon in gutter**
![2 click on the android icon in gutter](https://cloud.githubusercontent.com/assets/2944909/8762470/340fe292-2d97-11e5-9209-04b894cd386c.png)

**3 Subscriber is in the same file**
![3 Subscriber is in the same file](https://cloud.githubusercontent.com/assets/2944909/8762471/34b4f494-2d97-11e5-8101-33a3fe8a135c.png)

**4 Using eventbus 2.4.0**
![4 Using eventbus 2.4.0](https://cloud.githubusercontent.com/assets/2944909/8762468/33c8353c-2d97-11e5-89c1-a7122e06fa1b.png)

**Comment by kgmyshin** [comment]
@dheerajbhaskar

I fixed this issue.
I'd like you to confirm with following.

https://github.com/kgmyshin/eventbus-intellij-plugin/raw/master/eventbus-intellij-plugin.jar

If you will have problems, please reopen this.

thank you.

**Comment by dheerajbhaskar** [comment]
Thanks for the quick reply @kgmyshin ,  this fixes it. :+1: 

## Can you please consider the following things?
- Releasing this on the intellij repo? That way it auto updates.
- Make the search from onevent method to the post method faster? 
  - I can help with this. If you're aware of why it takes time (2-3s), I'd be happy to see if I can fix it.

Thanks again for the quick reply and for making this plugin :+1: :smile:

**Comment by kgmyshin** [comment]
@dheerajbhaskar 

Thank you!

> Releasing this on the intellij repo? That way it auto updates.

I already uploaded Intellij repo. But It takes time until it is approved.

> Make the search from onevent method to the post method faster?

I want to make searching faster. But I don't have idea. 
If I got your help, I'll be happy.

**Comment by dheerajbhaskar** [comment]
I'd be happy to help.
Right now, it's bothering me sometimes but not enough so I'll be motivated
enough once it becomes really annoying. Let me get to it then :-)
